export const graphTheory = {
  loading: "Cargando la guía de Teoría de grafos…",
  roadmap: "Ruta de aprendizaje",
  eyebrow: "Teoría de grafos · C++17",
  title: "Modela relaciones. Recorre con intención.",
  subtitle: "Los grafos convierten habitaciones, amistades, prerrequisitos y rutas en vértices y aristas. Aprende a elegir la representación y el recorrido que corresponde a la pregunta.",
  heroNoteTitle: "Base recomendada, acceso abierto",
  heroNote: "Estructuras de Datos es el prerrequisito recomendado porque pilas, colas y colas de prioridad impulsan estos recorridos. Esta guía permanece desbloqueada: puedes entrar cuando estos problemas te resulten útiles.",
  conceptsLabel: "Conceptos de Teoría de grafos",
  concepts: { model: "Modelar", traverse: "Recorrer", invariant: "Invariante", prove: "Demostrar" },
  sidebar: { label: "Secciones de la guía de Teoría de grafos", progress: "Sección {{current}} de {{total}}" },
  sections: { rooms: "Counting Rooms", labyrinth: "Labyrinth", teams: "Building Teams", schedule: "Course Schedule", routes: "Shortest Routes I", practice: "Práctica y comparación" },
  challenge: {
    constraints: "Restricciones", sample: "Ejemplo", source: "Abrir problema original", problemStage: "Problema",
    attempt: "Antes de revelar la herramienta, identifica los vértices y las aristas, y decide qué estado debe recordar cada vértice.", attemptStage: "Intento rápido",
    reveal: "Aprender la herramienta", hide: "Ocultar la herramienta", applicationPrompt: "Ahora conecta la herramienta general con este problema sin leer código de envío.",
    applicationReveal: "Mostrar la conexión con el problema", applicationHide: "Ocultar la conexión con el problema", toolStage: "Herramienta", applicationStage: "Aplicación"
  },
  conceptPlayers: {
    connectivity: {
      label: "DFS sigue una rama antes de retroceder", preset: "Recorrido DFS completo", description: "Un grafo ramificado de siete nodos muestra cada descenso, retroceso y rama terminada hasta visitar todos los nodos alcanzables.",
      start: "Comienza en el nodo 1 y apunta a su primer vecino no visitado, el nodo 2.", descend: "Entra al nodo {{vertex}}; su siguiente vecino no visitado es el nodo {{next}}.", leaf: "El nodo {{vertex}} no tiene vecinos sin visitar, así que DFS retrocede al nodo {{parent}}.", resume: "De vuelta en el nodo {{vertex}}, DFS continúa con el vecino no visitado {{next}}.", nextBranch: "Toda la rama del nodo 2 terminó; DFS regresa al nodo 1 y ahora apunta al nodo 3.", finished: "El nodo 7 completa la última rama. Todos los nodos alcanzables desde 1 están visitados y DFS termina."
    },
    bfs: {
      label: "BFS se expande por capas de distancia", preset: "Recorrido BFS completo", description: "El grafo cambia de color capa por capa mientras la cola FIFO, las distancias y los padres muestran el recorrido completo.", graph: "Grafo BFS y capas de distancia", distance: "Distancias", queue: "Cola FIFO", parents: "Enlaces de padres", source: "origen",
      initialize: "Inicializa el nodo origen 1 con distancia 0 y encólalo.", dequeue: "Desencola el nodo {{vertex}} e inspecciona todos sus vecinos.", discover: "Descubre el nodo {{vertex}} desde el nodo {{parent}} a distancia {{distance}}, registra su padre y encólalo.", finished: "La cola queda vacía solo después de procesar los siete nodos alcanzables; BFS termina."
    },
    adjacency: { label: "Una arista no dirigida aparece en ambas listas de adyacencia" },
    indegree: {
      label: "El grado de entrada dirige el orden topológico", successPreset: "DAG completo", successDescription: "Ejecuta Kahn hasta el final sobre un DAG ramificado y emite todos los nodos.", cyclePreset: "Fallo por ciclo", cycleDescription: "Un contraejemplo separado muestra por qué un ciclo dirigido impide cualquier orden topológico.",
      initialize: "Los nodos 1 y 2 tienen grado de entrada cero, así que ambos entran en la cola.", emitVertex: "Emite el nodo {{vertex}}, elimina todas sus aristas salientes y encola cada vecino cuyo grado de entrada llega a cero.", finished: "Se emitieron los cinco nodos; 1, 2, 3, 4, 5 es un orden topológico válido y completo.", cycleStart: "En este grafo separado, cada nodo tiene grado de entrada 1, así que la cola inicial está vacía.", cycle: "La cola está vacía pero quedan nodos. Las flechas forman un ciclo dirigido y no existe un orden topológico.", cycleLabel: "Contraejemplo con ciclo dirigido", queue: "Cola de grado cero", order: "Orden válido", leftovers: "Restantes del ciclo"
    },
    relaxation: {
      label: "Relaja distancias tentativas", preset: "Ejecución completa de Dijkstra", description: "Sigue cada operación de la cola de prioridad hasta fijar la ruta más barata de dos aristas y descartar la entrada obsoleta.",
      initialize: "Fija distancia[1] en 0, las demás en infinito e inserta 0:1.", settle: "Extrae {{distance}}:{{vertex}}; coincide con la distancia guardada, así que se procesa el nodo {{vertex}}.", direct: "Relaja 1 → 2 y registra la primera distancia tentativa 9.", intermediate: "Relaja 1 → 3 a distancia 2. La cola elige 2:3 antes que 9:2.", improve: "Desde el nodo 3, la ruta 1 → 3 → 2 cuesta 2 + 3 = 5 y mejora la distancia 9.", stale: "La entrada restante 9:2 está obsoleta. Se descarta sin resaltar ni procesar de nuevo el nodo 2.", finished: "La cola está vacía y las distancias finales son 0, 5, 2; Dijkstra termina."
    }
  },
  representations: {
    eyebrow: "Almacenamiento de grafos",
    title: "Representa el mismo grafo con una lista o una matriz",
    intro: "Un diagrama ayuda a una persona a ver un grafo, pero un algoritmo necesita una estructura de datos. Estas dos representaciones codifican el mismo grafo no dirigido de cinco nodos; elige según las operaciones y la densidad esperadas.",
    graphTitle: "Grafo de ejemplo",
    listTitle: "Lista de adyacencia",
    listText: "Guarda solo los vecinos de cada nodo. Usa O(n + m) de memoria y suele ser la mejor opción para grafos dispersos de competencia y recorridos que inspeccionan aristas salientes.",
    matrixTitle: "Matriz de adyacencia",
    matrixText: "Guarda una celda para cada par ordenado de nodos. Usa O(n²) de memoria, pero comprobar si existe una arista específica toma O(1).",
    matrixAria: "Matriz de adyacencia del ejemplo de cinco nodos",
    symmetry: "Como el ejemplo no es dirigido, cada arista u—v aparece dos veces: v está en la lista de u y u en la de v, mientras las celdas [u][v] y [v][u] valen 1. Un grafo dirigido registra solo el sentido de la flecha."
  },
  traces: {
    visuals: { grid: "Cuadrícula", graph: "Grafo", distance: "Distancia", queue: "Cola", priorityQueue: "Cola de prioridad", order: "Orden", adjacency: "Listas de adyacencia", stack: "Pila de llamadas", parent: "Mapa de padres", moves: "Movimientos" },
    labels: { gridDfs: "Búsqueda en profundidad sobre una lista de adyacencia", gridBfs: "Búsqueda en anchura con padres", bipartiteDfs: "DFS para coloreo bipartito", kahn: "Orden topológico de Kahn", dijkstra: "Dijkstra con cola de prioridad perezosa" },
    execution: {
      initialize: "Inicializa el estado del recorrido.", enter: "Entra en la siguiente llamada recursiva.", bounds: "Comprueba si fila {{row}}, columna {{column}} está fuera de límites.", wall: "La comprobación de pared da {{result}}.", visited: "La comprobación de visitado da {{result}}.", mark: "Marca fila {{row}}, columna {{column}} como visitada.", direction: "Inspecciona el siguiente vecino en el orden determinista.", recurse: "Llama recursivamente a {{value}}.", return: "Regresa de esta llamada recursiva.",
      enqueue: "Encola el elemento elegido para procesarlo después.", dequeue: "Elimina el elemento elegido de la frontera.", loop: "Continúa mientras la frontera no esté vacía.", front: "Lee {{value}} del frente.", neighbour: "Forma el vecino {{value}}.", distance: "Actualiza la distancia a {{distance}}.", parent: "Registra el padre {{value}}.", discover: "Descubre una celda nueva y registra distancia y padre.", reconstruct: "La cadena reconstruida es {{value}}.",
      colour: "Colorea el vértice {{vertex}} con el color opuesto requerido.", inspect: "Inspecciona la siguiente arista o vértice.", conflict: "Los vértices {{from}} y {{to}} tienen el mismo color; esta arista produce conflicto.",
      indegree: "Inspecciona la información actual de grados de entrada.", emit: "Emite el vértice {{vertex}} en el orden topológico.", decrement: "Elimina {{from}}→{{to}}; el grado pasa a {{indegree}}.",
      push: "Inserta ({{distance}}, {{vertex}}) en la cola de prioridad.", pop: "Extrae ({{distance}}, {{vertex}}), el menor par en cola.", stale: "Descarta la entrada obsoleta ({{distance}}, {{vertex}}).", candidate: "La distancia candidata es {{distance}}.", relax: "Relaja la arista hacia el vértice {{to}} y mejora la distancia a {{distance}}.", reject: "Rechaza la arista hacia el vértice {{to}} porque el candidato {{distance}} no mejora la distancia.", finished: "El algoritmo terminó."
    }
  },
  rooms: {
    eyebrow: "Cuadrícula como grafo implícito", title: "Counting Rooms", description: "Cuenta las regiones conectadas de suelo en un mapa rectangular. Dos celdas pertenecen a la misma habitación si un camino de celdas de suelo que comparten lado las une.",
    constraints: "1 ≤ n, m ≤ 1000; cada celda es suelo (.) o pared (#).", sample: "5 8\n########\n#..#...#\n####.#.#\n#..#...#\n########\n→ 3",
    toolTitle: "Recorre un grafo con búsqueda en profundidad", toolText: "DFS comienza en cualquier vértice origen, lo marca como visitado y sigue un vecino no visitado a la vez. La recursión o una pila explícita recuerda dónde regresar; el mismo algoritmo funciona con cualquier lista de adyacencia.",
    foundation: { title: "La herramienta reutilizable", node: { term: "Nodo (vértice)", definition: "Un objeto del modelo: persona, curso, ciudad, estado o celda." }, edge: { term: "Arista", definition: "Una relación que indica qué nodos son vecinos directos." }, dfs: { term: "Búsqueda en profundidad", definition: "Sigue una rama hasta el final y luego retrocede al siguiente vecino no visitado." } },
    applicationTitle: "Convierte cada inundación terminada en una habitación", explanation: "Recorre las celdas por filas. Cada celda de suelo no visitada demuestra que encontraste un componente nuevo: incrementa la respuesta y recórrelo, marcando todo el suelo alcanzable. Las paredes y celdas visitadas detienen una rama. Al terminar, imprime cuántos recorridos iniciaste.", animationLabel: "Escenarios de Counting Rooms",
    pitfalls: { correctness: "Corrección", correctnessText: "Cada inundación marca exactamente un componente conexo maximal; el barrido inicia una por componente y nunca dos para el mismo.", complexity: "Complejidad", complexityText: "O(nm) en tiempo y O(nm) para visitados: cada celda y vecino lateral se inspecciona un número constante de veces.", warning: "Seguridad de la pila", warningText: "Un solo componente de 1000 × 1000 puede desbordar la pila de C++. Usa DFS iterativo o BFS cuando la profundidad pueda acercarse al número de celdas." }
  },
  labyrinth: {
    eyebrow: "Camino mínimo en una cuadrícula sin pesos", title: "Labyrinth", description: "Encuentra cualquier ruta mínima de A a B por celdas abiertas e imprime la secuencia de movimientos.",
    constraints: "1 ≤ n, m ≤ 1000; hay exactamente una A y una B; el movimiento es ortogonal.", sample: "5 8\n########\n#.A#...#\n#.##.#B#\n#......#\n########\n→ YES, 9 movimientos",
    toolTitle: "Recorre un grafo no ponderado por capas BFS", toolText: "BFS parte de un vértice origen y usa una cola FIFO. El primer descubrimiento fija la distancia mínima en aristas; registra el padre en ese momento si también necesitas reconstruir un camino.",
    foundation: { title: "La herramienta reutilizable de caminos mínimos", bfs: { term: "Búsqueda en anchura", definition: "Visita todos los vértices a una arista antes que cualquiera a dos aristas." }, queue: { term: "Cola FIFO", definition: "Los vértices salen en orden de descubrimiento, conservando capas de distancia crecientes." }, parent: { term: "Enlace padre", definition: "La arista que descubrió primero un vértice; seguir padres reconstruye un camino mínimo." } },
    applicationTitle: "Reconstruye un camino mínimo aceptado", explanation: "Modela las celdas transitables como vértices unidos por aristas laterales de costo uno. Ejecuta BFS desde A y registra para cada primer descubrimiento el predecesor y movimiento usado. Si descubres B, sigue los padres hasta A, invierte los movimientos e imprime YES, la longitud y esa cadena; de lo contrario, imprime NO.", animationLabel: "Escenarios de Labyrinth",
    pitfalls: { correctness: "Corrección", correctnessText: "Las capas FIFO garantizan que el primer descubrimiento tiene el menor número de aristas; los padres forman un camino mínimo hasta A.", complexity: "Complejidad", complexityText: "O(nm) en tiempo y O(nm) en memoria.", warning: "Trazas deterministas", warningText: "El modelo, la herramienta, la animación y las pruebas usan abajo, arriba, derecha, izquierda. Otros órdenes pueden producir otro camino mínimo, y cualquiera se acepta." }
  },
  teams: {
    eyebrow: "Listas de adyacencia y dos colores", title: "Building Teams", description: "Asigna cada estudiante a uno de dos equipos para que ninguna amistad tenga ambos extremos en el mismo equipo.",
    constraints: "1 ≤ n, m ≤ 100000; las amistades no son dirigidas; el grafo puede estar desconectado.", sample: "5 3\n1 2\n1 3\n4 5\n→ 1 2 2 1 2",
    toolTitle: "Prueba un grafo con bicoloreo", toolText: "Inicia un componente sin color con cualquiera de los dos colores. DFS o BFS da el color opuesto a cada vecino recién descubierto; reinicia en cada nodo aún sin color para incluir componentes desconectados y nodos aislados.",
    foundation: { title: "La prueba reutilizable de bicoloreo", bipartite: { term: "Grafo bipartito", definition: "Sus nodos se pueden separar en dos grupos de modo que cada arista cruce de un grupo al otro." }, twoColour: { term: "Bicoloreo", definition: "Da a cada vecino el color opuesto al del nodo actual mientras recorres el grafo." }, conflict: { term: "Arista en conflicto", definition: "Una arista cuyos extremos ya tienen el mismo color demuestra que no existe un bicoloreo válido." } },
    applicationTitle: "Interpreta un conflicto como ciclo impar", explanation: "Construye una lista de adyacencia no dirigida. Desde cada vértice aún sin color, inicia un recorrido con el equipo A; cada arista obliga al otro extremo a usar el equipo contrario. Si un vecino ya coloreado tiene el mismo color, imprime IMPOSSIBLE. Si no, imprime el equipo de cada vértice.", animationLabel: "Escenarios de Building Teams",
    pitfalls: { correctness: "Corrección", correctnessText: "Los colores opuestos satisfacen cada arista explorada. Un grafo es bipartito si y solo si no tiene un ciclo impar; una arista con colores iguales certifica la imposibilidad.", complexity: "Complejidad", complexityText: "O(n + m) en tiempo y O(n + m) en almacenamiento.", warning: "Desconexión y profundidad", warningText: "Inicia desde cada componente, incluso vértices aislados. Con n = 100000, DFS recursivo puede desbordar la pila de C++; una pila explícita o BFS es más seguro." }
  },
  schedule: {
    eyebrow: "Prerrequisitos dirigidos", title: "Course Schedule", description: "Ordena todos los cursos para que cada prerrequisito aparezca antes del curso que depende de él, o informa que no existe orden.",
    constraints: "1 ≤ n, m ≤ 100000; cada arista dirigida a → b exige a antes de b.", sample: "5 3\n1 2\n3 1\n4 5\n→ 3 4 1 5 2",
    toolTitle: "Ordena un DAG con el algoritmo de Kahn", toolText: "Kahn elimina repetidamente un vértice de grado de entrada cero. Quitar sus aristas salientes puede revelar nuevos vértices con grado cero; si quedan vértices al vaciarse la cola, existe un ciclo dirigido.",
    foundation: { title: "El modelo reutilizable de ordenamiento", directed: { term: "Grafo dirigido", definition: "Una arista u → v tiene dirección: se recorre de u a v, no automáticamente al revés." }, dag: { term: "DAG", definition: "Un grafo dirigido acíclico: seguir flechas nunca permite volver al nodo inicial." }, indegree: { term: "Grado de entrada", definition: "Número de aristas entrantes que conserva un nodo; cero significa que nada debe precederlo." } },
    applicationTitle: "Deja que la longitud del resultado revele ciclos", explanation: "Construye listas dirigidas y grados de entrada iniciales. Encola en orden ascendente cada curso de grado cero. Emite repetidamente el frente y reduce el grado de sus vecinos salientes, encolándolos al llegar a cero. Imprime el orden solo si contiene todos los cursos.", animationLabel: "Escenarios de Course Schedule",
    pitfalls: { correctness: "Corrección", correctnessText: "Un vértice de grado cero no tiene prerrequisitos pendientes, por lo que añadirlo conserva la validez. Existe un orden válido si y solo si el grafo es un DAG.", complexity: "Complejidad", complexityText: "O(n + m) en tiempo y O(n + m) en memoria.", warning: "Los restantes muestran la obstrucción", warningText: "Si se emiten menos de n vértices, toda región restante depende de un ciclo dirigido; informa IMPOSSIBLE." }
  },
  routes: {
    eyebrow: "Aristas con peso no negativo", title: "Shortest Routes I", description: "Encuentra el costo mínimo desde la ciudad 1 a cada ciudad en un grafo dirigido con pesos positivos.",
    constraints: "1 ≤ n ≤ 100000, 1 ≤ m ≤ 200000; 1 ≤ peso ≤ 10⁹; toda ciudad es alcanzable desde 1.", sample: "3 4\n1 2 6\n1 3 2\n3 2 3\n1 3 4\n→ 0 5 2",
    toolTitle: "Encuentra caminos mínimos en un grafo ponderado no negativo", toolText: "Dijkstra guarda la mejor distancia tentativa descubierta para cada nodo. Una cola de prioridad mínima elige la menor y la relajación pregunta si una arista saliente produce una ruta más barata.",
    foundation: { title: "El modelo reutilizable de caminos ponderados", weighted: { term: "Grafo ponderado", definition: "Cada arista tiene un costo como distancia, tiempo o precio; el costo de un camino es la suma de sus aristas." }, relaxation: { term: "Relajación", definition: "Prueba distancia[u] + peso(u,v) y reemplaza distancia[v] solo si el candidato es menor." }, nonnegative: { term: "Pesos no negativos", definition: "Dijkstra exige pesos al menos cero para que un mínimo fijado no pueda mejorar después." } },
    applicationTitle: "Usa los pesos para elegir el algoritmo", explanation: "Construye una lista dirigida con pesos e inicializa la ciudad 1 con distancia cero. Extrae el menor par y omítelo si ya existe una distancia mejor. Para cada vuelo saliente, reemplaza y agrega la distancia de destino solo si la nueva suma es menor. Imprime el arreglo final.", animationLabel: "Escenarios de Shortest Routes",
    correction: "Usa BFS para aristas sin peso o de igual peso, Dijkstra para pesos no negativos y Bellman–Ford u otro método adecuado cuando pueda haber aristas negativas.",
    pitfalls: { correctness: "Corrección", correctnessText: "Con pesos no negativos, la menor distancia no obsoleta de la cola no puede mejorar después, y la relajación conserva la mejor ruta descubierta.", complexity: "Complejidad", complexityText: "O((n + m) log n) en tiempo y O(n + m) en memoria con listas de adyacencia y heap binario.", warning: "Seguridad numérica y de la cola", warningText: "Usa long long porque las sumas superan int. Omite las entradas obsoletas; son normales en la implementación perezosa, no un error." }
  },
  scenarios: {
    common: { distance: "distancia", queue: "Cola", order: "Orden", impossible: "IMPOSSIBLE", final: "Terminado." },
    rooms: { sample: { label: "Muestra oficial", description: "Tres componentes separados por paredes." }, diagonal: { label: "Contacto diagonal", description: "Las esquinas no conectan habitaciones." }, winding: { label: "Habitación sinuosa", description: "Un pasillo estrecho sigue siendo un componente." } },
    labyrinth: { sample: { label: "Muestra oficial", description: "Alcanza B por un camino mínimo." }, unreachable: { label: "Ruta bloqueada", description: "Ningún camino cruza la pared." }, multipath: { label: "Varios caminos mínimos", description: "El orden determinista elige uno." } },
    teams: { sample: { label: "Muestra desconectada", description: "Colorea cada componente." }, oddCycle: { label: "Ciclo impar", description: "Colores iguales revelan un conflicto." }, evenCycle: { label: "Ciclo par y aislado", description: "Ambos son bipartitos." } },
    schedule: { sample: { label: "Muestra oficial", description: "El desempate FIFO da un orden determinista." }, multiple: { label: "Varios órdenes válidos", description: "Un orden válido determinista basta." }, cycle: { label: "Ciclo dirigido", description: "Ningún vértice alcanza grado de entrada cero." } },
    routes: { sample: { label: "Vuelos paralelos", description: "La ruta barata puede usar una ciudad intermedia." }, detour: { label: "Desvío más barato", description: "Dos aristas ligeras vencen una pesada." }, stale: { label: "Entrada obsoleta", description: "Una mejora posterior deja un par viejo en el heap." } },
    adjacency: { label: "Listas de amistad", description: "Cada amistad se almacena en ambos extremos.", frame: "Añade la amistad {{from}}—{{to}} a ambas listas.", finished: "Cada amistad no dirigida aparece dos veces, una desde cada extremo." },
    narration: {
      roomsVisit: "Visita fila {{row}}, columna {{column}} en la habitación {{room}}.", roomsComplete: "Terminó el componente {{room}}; ahora hay {{count}} habitaciones.", roomsFinal: "El barrido termina con {{count}} habitaciones.",
      bfsVisit: "Extrae fila {{row}}, columna {{column}} a distancia {{distance}}.", bfsPath: "Reconstruye el camino mínimo por fila {{row}}, columna {{column}}.", bfsFinal: "La distancia mínima es {{distance}} con movimientos {{moves}}.", bfsUnreachable: "La cola se vacía antes de alcanzar B, así que no existe camino.",
      colour: "Colorea el vértice {{vertex}} con el equipo {{colour}}.", conflict: "La arista {{from}}—{{to}} une colores iguales; la asignación es imposible.", teamsFinal: "La asignación completa es {{assignment}}.",
      enqueue: "Encola el vértice {{vertex}} porque su grado de entrada es cero.", dequeue: "Extrae y emite el vértice {{vertex}}.", decrement: "Elimina {{from}}→{{to}}; el grado de {{to}} ahora es {{indegree}}.", scheduleFinal: "El orden válido es {{order}}.", scheduleCycle: "Los vértices {{vertices}} nunca llegan a grado cero; un ciclo impide el orden.",
      push: "Inserta el vértice {{vertex}} con distancia tentativa {{distance}}.", pop: "Extrae el vértice {{vertex}} a distancia {{distance}}.", stale: "Descarta la entrada obsoleta ({{distance}}, {{vertex}}) porque ya se conoce una distancia mejor.", relax: "Relaja {{from}}→{{to}} y mejora la distancia a {{distance}}.", reject: "Rechaza {{from}}→{{to}} porque el candidato {{distance}} no mejora la distancia.", routesFinal: "Las distancias finales desde la ciudad 1 son {{distances}}."
    }
  },
  practice: { intro: "Modela antes de programar. Estos problemas cambian la pregunta del grafo, pero conservan representaciones e invariantes.", tag: "Práctica de grafos", links: { messageRoute: "Message Route", roundTrip: "Round Trip", monsters: "Monsters", highScore: "High Score", flightDiscount: "Flight Discount", maze: "Labyrinth" } },
  comparison: { eyebrow: "Herramientas cercanas de caminos mínimos", title: "Elige según las aristas y consultas", intro: "Floyd–Warshall sirve para todos los pares en grafos pequeños y densos. Bellman–Ford admite aristas negativas y detecta ciclos negativos alcanzables; ninguno requiere un arco completo aquí.", algorithm: "Algoritmo", applies: "Cuándo aplica", complexity: "Complejidad", floyd: { name: "Floyd–Warshall", applies: "Todos los pares; n pequeño; admite aristas negativas sin ciclo negativo", complexity: "O(n³) en tiempo, O(n²) en memoria" }, bellman: { name: "Bellman–Ford", applies: "Una fuente con aristas negativas; detecta ciclos negativos", complexity: "O(nm) en tiempo, O(n) en memoria" }, dijkstra: { name: "Dijkstra", applies: "Una fuente con pesos no negativos", complexity: "O((n + m) log n) en tiempo" } },
  finish: { eyebrow: "Herramientas de grafos listas", title: "Ya puedes convertir relaciones en invariantes.", description: "Lleva primero la decisión de modelado: define vértices y aristas, elige el estado y demuestra por qué el orden del recorrido responde el problema.", markComplete: "Marcar como completada", markProgress: "Marcar en progreso", back: "Volver a la ruta" },
  progress: { saveError: "No se inició el progreso", saveErrorDescription: "Puedes seguir leyendo e intentarlo después.", completed: "Teoría de grafos completada", completedDescription: "Teoría de grafos ahora cuenta en tu ruta.", inProgress: "Teoría de grafos reabierta", inProgressDescription: "La guía volvió a estar en progreso.", updateError: "No se actualizó el progreso", updateErrorDescription: "Tu estado anterior no cambió." }
} as const;
