export const introduction = {
  loading: "Cargando la guía de Introducción...",
  roadmap: "Ruta de aprendizaje",
  eyebrow: "Clase 01 · Introducción",
  title: "Entra a la sala de competencia.",
  subtitle: "Aprende cómo funciona la programación competitiva, instala C++, juega tres juegos de estrategia y envía tu primera solución a un Juez.",
  routeLabel: "Ruta de la clase",
  routeProgress: "Parada {{current}} de {{total}}",
  sections: {
    mentalModel: "Cómo funciona", icpc: "Dentro de ICPC", plate: "Juego de platos", languages: "Lenguajes de programación", setup: "Instala C++", stones: "25 piedras", codeforces: "Entender Codeforces", practice: "Cómo practicar", chomp: "Chomp", roadmap: "Qué sigue"
  },
  mentalModel: {
    kicker: "Modelo mental", title: "Cómo funciona la programación competitiva.",
    p1: "Los Problemas de programación competitiva usan una estructura constante. Recorre el Problema exacto que enviarás más adelante para entender qué aporta cada sección antes de escribir código.",
    problemTitle: "A. Watermelon",
    timeLimitLabel: "Límite de tiempo por prueba", timeLimit: "1 segundo", memoryLimitLabel: "Límite de memoria por prueba", memoryLimit: "64 megabytes",
    limitsGuide: "Los límites indican cuánto puede tardar el programa y cuánta memoria puede usar. Sirven para decidir si un enfoque es viable.",
    statementTitle: "Enunciado",
    statementP1: "Un caluroso día de verano, Pete y su amigo Billy decidieron comprar una sandía. Eligieron la más grande y madura, según ellos. Al pesarla, la balanza marcó w kilos. Corrieron a casa y decidieron dividirla, pero se encontraron con un problema.",
    statementP2: "Pete y Billy quieren dividir la sandía de modo que cada una de las dos partes pese un número par de kilos. Las partes no tienen que ser iguales, pero cada persona debe recibir una parte de peso positivo. Determina si pueden dividir la sandía de esta manera.",
    statementGuide: "La historia aporta contexto; la tarea dentro de ella es decidir si un peso puede convertirse en dos pesos positivos y pares.",
    inputTitle: "Entrada", inputText: "La primera y única línea de entrada contiene el entero w (1 ≤ w ≤ 100), el peso de la sandía en kilos.",
    inputGuide: "La sección Entrada define exactamente qué lee el programa. Aquí lee un entero y la restricción indica que todos los valores posibles están entre 1 y 100.",
    outputTitle: "Salida", outputText: "Imprime YES si la sandía puede dividirse en dos partes que pesen un número par de kilos; de lo contrario, imprime NO.",
    outputGuide: "La sección Salida define la respuesta y su escritura exacta. Imprimir una explicación en lugar de exactamente YES o NO sería considerado incorrecto.",
    exampleTitle: "Ejemplo", sampleInputLabel: "Entrada", sampleInput: "8", sampleOutputLabel: "Salida", sampleOutput: "YES",
    noteTitle: "Nota.", noteText: "Una sandía de 8 kilos puede dividirse en 2 y 6 kilos, o en 4 y 4 kilos.",
    exampleGuide: "El ejemplo muestra una entrada válida y su salida esperada. Ayuda a confirmar que entendiste la tarea, pero el Juez también probará casos que no aparecen aquí.",
    p2: "Usa el enunciado, las restricciones y los ejemplos para entender qué debe hacer el programa antes de escribir código. Una sandía de peso 8 puede dividirse en 4 y 4, así que la respuesta es YES. Una de peso 2 no puede dividirse en dos pesos positivos y pares, así que la respuesta es NO.",
    p3: "A partir de esos casos puedes deducir la regla: el peso debe ser par y mayor que 2. Después expresas esa regla en C++, compilas y pruebas localmente con entradas como 8 y 2. El código completo y los comandos aparecen más adelante en la sección del primer envío.",
    p4: "Cuando envías la solución, el Juez compila el código fuente y lo ejecuta con entradas ocultas dentro de límites fijos de tiempo y memoria. Devuelve un veredicto que indica si el programa fue aceptado o si debes revisar la compilación, la salida, la velocidad o el comportamiento durante la ejecución.",
    verdictsTitle: "Veredictos del Juez",
    verdicts: { ac: "AC · Accepted — correcto en todas las pruebas", wa: "WA · Wrong Answer — la salida es diferente", tle: "TLE · Time Limit Exceeded — demasiado lento", rte: "RTE · Runtime Error — falló durante la ejecución", ce: "CE · Compilation Error — el código no compiló" }
  },
  icpc: {
    kicker: "Competencia", title: "ICPC es un juego de estrategia en equipo de cinco horas.",
    p1: "En una competencia ICPC, un equipo universitario de tres personas comparte un computador. Los equipos eligen qué Problemas atacar, comunican ideas parciales, depuran bajo presión y envían soluciones a un Juez durante cinco horas.",
    p2: "La clasificación empieza por cantidad de Problemas resueltos y luego por tiempo de penalización. Las competencias regionales conducen a etapas posteriores. El formato premia los roles claros y las buenas decisiones tanto como escribir rápido.",
    p3: "Los equipos fuertes mantienen una visión compartida de la competencia. Una persona puede leer un enunciado mientras otra valida una idea y quien está en el computador implementa la solución más prometedora. Los roles cambian cuando aparece información nueva.",
    p4: "Un envío rechazado consume tiempo y atención, por eso el equipo prueba sus supuestos antes de enviar. También vuelve a Problemas parcialmente resueltos cuando surge una observación nueva, en lugar de abandonar después del primer intento.",
    levelsTitle: "Niveles de competencia ICPC",
    levels: {
      university: { title: "Competencia interna universitaria", description: "Los estudiantes forman equipos y compiten dentro de su universidad. Las instituciones suelen usar esta etapa para seleccionar representantes y familiarizar a los equipos nuevos con el formato ICPC." },
      national: { title: "Competencia nacional", description: "Los equipos se enfrentan a universidades de todo el país. Según la ruta local, esta etapa puede definir un título nacional, funcionar como clasificatoria o cumplir ambos objetivos." },
      regional: { title: "Competencia regional", description: "Los equipos universitarios compiten en una competencia regional oficial de ICPC. Los resultados determinan qué equipos pueden avanzar por la ruta de clasificación de su región." },
      regionalChampionship: { title: "Campeonato regional", description: "Cuando la región incluye esta etapa, los mejores equipos de sus clasificatorias se reúnen en un campeonato que determina o ayuda a determinar la clasificación a la Final Mundial." },
      worldFinals: { title: "Final mundial", description: "Los equipos clasificados de las regiones ICPC de todo el mundo se reúnen para el campeonato global y compiten con el formato completo de cinco horas." }
    },
    official: "Lee la descripción oficial de ICPC", statTeam: "3 personas", statComputer: "1 computador", statTime: "5 horas"
  },
  plateLesson: { kicker: "Pausa de juego", title: "Juego de platos.", intro: "Dos jugadores colocan círculos de radio uno sobre un tablero que comienza en 7×7; cambia su ancho y alto en el juego para explorar otros rectángulos. Los círculos pueden tocarse, pero no superponerse ni cruzar el borde. Quien haga la última colocación legal gana.", p2: "Haz clic en cualquier punto del tablero para intentar una colocación. Un centro legal debe quedar al menos a una unidad de cada borde y a dos unidades de cualquier centro existente. Un clic inválido no cambia el tablero ni el turno." },
  languages: {
    title: "Lenguajes de programación.",
    intro: "Un lenguaje de programación es la notación que usas para expresar un algoritmo. El Juez admite varios lenguajes, pero cada compilador o entorno de ejecución tiene distinta velocidad, uso de memoria, bibliotecas y sintaxis.",
    cppTitle: "C++",
    pythonTitle: "Python",
    prosTitle: "Ventajas",
    consTitle: "Desventajas",
    cppPros: {
      speed: "Su ejecución rápida y control preciso de memoria lo hacen confiable con límites ajustados y entradas grandes.",
      library: "La biblioteca estándar ofrece contenedores y algoritmos eficientes que se usan con frecuencia en competencias.",
      debugging: "Los tipos estáticos permiten que el compilador detecte muchos errores antes de ejecutar el programa, lo que suele facilitar la depuración en C++."
    },
    cppCons: {
      syntax: "Las soluciones suelen ser más largas y requieren más sintaxis que programas equivalentes en Python.",
      safety: "Los índices, el acceso a memoria y los tipos numéricos pueden causar errores sutiles si se usan sin cuidado."
    },
    pythonPros: {
      concise: "Su sintaxis concisa permite convertir rápidamente una idea clara en código fuente.",
      features: "El soporte integrado para enteros grandes y las operaciones expresivas con strings y colecciones pueden simplificar una solución.",
      useCases: "Funciona bien para simulaciones sencillas y algoritmos que caben cómodamente en los límites."
    },
    pythonCons: {
      performance: "Su ejecución más lenta y mayor uso de memoria pueden ser riesgosos con entradas grandes o algoritmos exigentes.",
      types: "Los tipos dinámicos hacen que algunos errores de tipo aparezcan solo cuando el programa llega a ese código durante la ejecución."
    },
    choice: "Usa C++ como opción predeterminada mientras aprendes en este curso. Elige Python cuando haga la solución mucho más clara y las restricciones dejen tiempo suficiente para ejecutarla. El algoritmo importa más que el lenguaje, pero los límites determinan qué implementaciones son viables."
  },
  setup: {
    kicker: "Entorno", title: "Instala C++.",
    intro: "Elige la ruta compatible con tu equipo. Lee qué cambia el script, descárgalo desde esta aplicación, ejecútalo tú mismo y verifica la ruta y versión del compilador que imprime al final. ICPC Trainer nunca ejecuta estos archivos.",
    p2: "El editor y el compilador cumplen funciones diferentes. VS Code ayuda a navegar y editar archivos; g++ traduce C++ a un programa que tu equipo puede ejecutar.",
    p3: "Trata la instalación como una secuencia de verificaciones observables. Confirma que cada comando termine, abre una terminal nueva para cargar los cambios del PATH y compila un programa pequeño antes de depender del entorno en una competencia.",
    windows: "Windows", windowsSupport: "Compatible cuando WinGet está disponible", windowsChanges: "Instala o reutiliza VS Code, instala MSYS2 UCRT64 GCC/g++ y Microsoft C/C++, agrega el compilador y VS Code al PATH de tu usuario y configura IntelliSense para usar el compilador.",
    windowsCommand: "Set-ExecutionPolicy -Scope Process Bypass; & \"$HOME\\Downloads\\install-cpp-vscode.ps1\"",
    mac: "macOS · solo Apple Silicon", macSupport: "Los Mac Intel no son compatibles en esta versión", macChanges: "Instala o inicializa Homebrew, VS Code, Microsoft C/C++, GCC de Homebrew y valores de IntelliSense para Apple Silicon.", macCommand: "bash \"$HOME/Downloads/install-cpp-vscode-macos.sh\"",
    inspect: "Qué cambia este script", viewSource: "Ver código fuente", download: "Descargar instalador", verify: "Al terminar imprime la ruta del compilador y g++ --version. Abre una terminal nueva si el PATH aún no se actualiza.", recoveryTitle: "Notas de recuperación",
    windowsRecovery: "Si falta WinGet, instala App Installer de Microsoft. Si falla un paquete o el paso de JSON de VS Code, corrige ese mensaje y vuelve a ejecutar el script idempotente. Reinicia la terminal después de cambiar el PATH.",
    macRecovery: "El script se detiene en un Mac que no sea arm64. Corrige fallas de Homebrew o de red y vuelve a ejecutarlo. Si el JSON de configuración es inválido, repáralo primero. Una ruta GCC ausente suele indicar que Homebrew no terminó.",
    fallbackTitle: "¿Bloqueado? Termina la clase en línea.", fallback: "Usa el IDE de USACO Guide solo como último recurso. Permite que estudiantes con Mac Intel o bloqueos temporales terminen la clase, pero un editor y compilador local es el mejor entorno de práctica a largo plazo.", fallbackLink: "Abrir el IDE de USACO Guide"
  },
  stonesLesson: { kicker: "Pausa de juego", title: "25 piedras.", intro: "Toma una, dos o tres piedras en tu turno. Quien toma la última gana. Busca posiciones donde cada jugada entrega el control al siguiente jugador.", optimalPlay: "Si ambos jugadores juegan de forma óptima, gana el Jugador 1. Primero toma una piedra y deja 24. Después de que el Jugador 2 tome una, dos o tres piedras, el Jugador 1 toma las necesarias para que ambos turnos retiren cuatro piedras en total. Al repetir esta respuesta, el Jugador 1 termina tomando la última piedra." },
  codeforces: {
    kicker: "Flujo del Juez", title: "Entender Codeforces.", intro: "Esta solución guiada enseña el flujo del Juez; Fundamentos de programación es donde comienza la instrucción independiente de C++.", p2: "Un envío combina tres decisiones: el Problema, el archivo fuente y el compilador. Si una es incorrecta, incluso un programa correcto puede producir un resultado confuso; verifica las tres antes de enviar.", p3: "El veredicto es evidencia, no una calificación. Úsalo para elegir el siguiente paso: una falla de compilación apunta a la construcción, Wrong Answer a la lógica o el formato, y los errores de ejecución o tiempo al comportamiento del programa.",
    signupTitle: "Crea tu cuenta de Codeforces", signupIntro: "El registro es gratuito. Usa un correo electrónico al que tengas acceso y elige tu handle con cuidado porque será tu identidad pública en Codeforces.", signupStep1: "Abre la página de registro de Codeforces y elige un handle disponible.", signupStep2: "Ingresa tu correo y crea una contraseña segura que no reutilices en otro servicio.", signupStep3: "Completa la verificación que muestre Codeforces y sigue las instrucciones que te envíe para la cuenta.", signupStep4: "Inicia sesión y abre tu perfil para confirmar que tu handle y tu cuenta estén listos antes del primer Contest.", signupLink: "Crear una cuenta de Codeforces",
    anatomyTitle: "Ubícate en Codeforces", anatomyIntro: "Estas tres áreas organizan distintos tipos de práctica. Aprende para qué sirve cada página antes de elegir un Problema, así entrarás con el objetivo y las expectativas correctas.", contests: "Contests", contestsText: "Contests reúne competencias próximas, actuales y pasadas. Las divisiones de Codeforces agrupan las competencias según el nivel de experiencia esperado: Div. 4 es la más accesible, Div. 3 es el siguiente paso, Div. 2 exige más experiencia y Div. 1 está dirigida a los competidores más fuertes. Comienza con una competencia Div. 4 y concéntrate en resolver los primeros Problemas; avanza cuando ese nivel te resulte cómodo. Algunas competencias combinan divisiones o aplican reglas de elegibilidad distintas, así que lee siempre el anuncio de cada competencia.", difficultyTitle: "¿Qué tan difícil es un contest?", difficultyText: "La división del contest y los requisitos de rating indican el rango de participantes para el que fue diseñado. Las letras de los Problemas suelen avanzar de los más accesibles a los más exigentes, pero el orden es solo una señal aproximada porque la dificultad depende de las ideas que reconozcas. Después del contest, el rating individual de cada Problema es una mejor guía para elegir práctica cercana a tu nivel actual.", gym: "Gym", gymText: "Gym contiene conjuntos archivados y comunitarios, a menudo organizados para práctica estilo ICPC o en equipo. Sus estrellas son una guía aproximada de la dificultad de toda la sesión: 1 estrella es la más accesible, 2 estrellas son adecuadas para equipos en formación, 3 estrellas indican un nivel intermedio, 4 estrellas un nivel avanzado y 5 estrellas los conjuntos más difíciles. Comienza con un Gym de 1 o 2 estrellas y avanza cuando tu equipo pueda resolver varios Problemas bajo presión de tiempo. La valoración describe el conjunto completo, por lo que la dificultad de cada Problema puede variar mucho.", problemset: "Problemset", problemsetText: "Problemset es el catálogo de búsqueda para la práctica individual. Filtra por rating y tags; después lee el enunciado, la entrada, la salida, las restricciones y los ejemplos antes de programar. Tras un intento serio, usa submissions y editorials para diagnosticar qué te faltó y luego vuelve a implementar la idea por tu cuenta.",
    languageTitle: "Conecta el código con el compilador", cpp: "Código C++ → GNU G++. Usa un compilador GNU C++ para que el envío coincida con la herramienta g++ local y admita <bits/stdc++.h>.", python: "Código Python → Python 3 o PyPy 3. PyPy es otro entorno de ejecución para código Python, no otro lenguaje fuente.", compilerList: "Ver la lista de compiladores mantenida por Codeforces",
    stepsTitle: "Tu primer envío", step1: "1 · Inicia sesión y abre el Problema 4A, “Watermelon”.", step2: "2 · Copia el código incluido en main.cpp.", step3: "3 · Compila localmente. La entrada 8 debe imprimir YES.", windowsCompile: "Windows · PowerShell", windowsCompileCommand: "g++ -O2 -Wall main.cpp -o main.exe\n\"8\" | .\\main.exe", macCompile: "Apple Silicon · Terminal", macCompileCommand: "GXX=\"/opt/homebrew/bin/g++-$(brew list --versions gcc | awk 'NR == 1 { split($2, v, \".\"); print v[1] }')\"\n\"$GXX\" -O2 -Wall main.cpp -o main\nprintf '8\\n' | ./main", step4: "4 · Elige un compilador GNU G++ y pega o sube el código.", step5: "5 · Envía y espera el veredicto Accepted observable.", problemLink: "Abrir Codeforces 4A", recoveryTitle: "Recuperación por veredicto", recovery: "CE: confirma que elegiste GNU G++ y copiaste todo el código. WA: prueba 8 → YES y 2 → NO. RTE: vuelve a copiar la solución conocida. TLE: confirma que enviaste esta solución de tiempo constante. Si Codeforces no está disponible, conserva el código y termina después el paso externo."
  },
  practice: {
    kicker: "Hábito", title: "Cómo practicar.", intro: "Desarrolla habilidades de resolución de problemas resolviendo muchos Problemas con trabajo aleatorio en Problemset, Contests en vivo o virtuales y Gyms en equipo. Mantén cada Problema no resuelto en una lista personal de upsolving hasta entenderlo y conseguir un veredicto Accepted.", p2: "Elige Problemas que exijan una observación nueva, pero que estén lo bastante cerca de tu nivel para avanzar. Si todo es inmediato, aumenta la dificultad; si cada sesión termina sin una idea concreta, reduce temporalmente la distancia.", p3: "Para cada Problema no resuelto, registra qué intentaste y dónde falló el razonamiento. Después, empieza a leer el editorial y detente en cuanto te dé una idea nueva para explorar. Intenta desarrollar esa idea por tu cuenta antes de seguir leyendo. Más tarde, reimplementa sin copiar y explica por qué la solución cumple las restricciones antes de cerrar el elemento.", doctrine: "Intentar → registrar → aprender → reimplementar → aceptar", note: "Las pistas y editoriales pueden apoyar el aprendizaje; copiar una respuesta no cierra el elemento. Esta lista personal es un método de práctica, no una promesa de que ICPC Trainer pueda agregar manualmente cualquier Problema de Codeforces hoy."
  },
  chompLesson: { kicker: "Juego final", title: "Chomp.", intro: "Elige un cuadro de chocolate para quitarlo junto con todo lo que está debajo y a su derecha. El cuadro superior izquierdo está envenenado: quien lo elige pierde de inmediato.", p2: "El objeto importante no es el último mordisco, sino la forma restante. Dos secuencias que dejan las mismas longitudes de fila llegaron al mismo estado y deben producir el mismo ganador con juego perfecto.", p3: "Razona hacia atrás desde tableros pequeños. Si un estado tiene una mordida segura hacia una posición donde el siguiente jugador acabará perdiendo, llámalo ganador; si todas las mordidas seguras entregan una posición ganadora, llámalo perdedor. Usa esa definición sin pedir una jugada." },
  future: {
    kicker: "Dirección", title: "Tus próximos diez Temas de aprendizaje.", intro: "Esta secuencia presenta los temas que seguirán a esta Introducción. Las guías todavía están en preparación y estarán disponibles más adelante.", p2: "Los temas se refuerzan entre sí. La complejidad permite descartar enfoques que no caben en los límites; las estructuras de datos abaratan operaciones repetidas; búsqueda, greedy y programación dinámica organizan distintos tipos de decisiones.", p3: "Por ahora, conserva esta Introducción como referencia para el ciclo del Juez y el método de práctica, y refuérzala escribiendo programas pequeños y resolviendo Problemas para principiantes.", available: "Disponible", future: "Guía futura", fundamentals: "Fundamentos", complexity: "Teoría de complejidad", dataStructures: "Estructuras de datos", bruteForce: "Fuerza bruta", binarySearch: "Búsqueda binaria", dynamicProgramming: "Programación dinámica", greedy: "Greedy", graphs: "Grafos", strings: "Strings", geometry: "Geometría"
  },
  games: {
    player: "Jugador {{player}}", active: "Turno del jugador {{player}}", winner: "El jugador {{player}} gana", reset: "Reiniciar juego", showStrategy: "Explicar cómo razonar sobre el ganador", hideStrategy: "Ocultar explicación del ganador", invalid: "Esa jugada sale de la mesa o se superpone con otro plato. El jugador {{player}} conserva el turno.",
    plate: { label: "Tablero de {{width}} por {{height}} del Juego de platos", mouseInstruction: "Elige el ancho y el alto del tablero; luego mueve el puntero sobre él para previsualizar un círculo de radio uno. Haz clic o toca para colocarlo; una previsualización roja no es legal. Con el teclado, enfoca el tablero, mueve la previsualización con las flechas y presiona Enter o Espacio para colocarla.", dimensions: "Dimensiones del tablero", width: "Ancho del tablero", height: "Alto del tablero", resized: "El tablero cambió a {{width}} por {{height}}. Comenzó una partida nueva.", moves: "{{count}} colocaciones válidas", placed: "El jugador {{player}} colocó un plato. Sigue el jugador {{next}}.", won: "El jugador {{player}} colocó el último plato legal y gana.", strategy: "Para razonar sobre el ganador, busca una simetría o emparejamiento que permita responder cada jugada legal con otra jugada legal. Las respuestas aparecen en pares. Si alguien puede establecer ese emparejamiento después de una colocación sin pareja, controla quién hace la última jugada. Comprueba los bordes y superposiciones sin buscar una coordenada revelada." },
    stones: { label: "Juego de 25 piedras", remaining: "Quedan {{count}} piedras", take: "Tomar {{count}}", moved: "El jugador {{player}} tomó {{count}}. Sigue el jugador {{next}}.", won: "El jugador {{player}} tomó la última piedra y gana.", lastMove: "Última jugada: {{count}} piedras", strategy: "Clasifica los tamaños desde el menor. Un montón es ganador cuando alguna remoción entrega al oponente un montón perdedor, y es perdedor cuando todas entregan uno ganador. Las etiquetas se repiten en grupos de cuatro, así que la etiqueta inicial indica quién puede forzar la última piedra sin revelar qué jugada hacer." },
    chomp: { label: "Tablero de Chomp de 5 por 7", square: "Fila {{row}}, columna {{column}}", poison: "Veneno en fila 1, columna 1", remaining: "Quedan {{count}} cuadros de chocolate", bite: "El jugador {{player}} mordió fila {{row}}, columna {{column}}. Sigue el jugador {{next}}.", poisoned: "El jugador {{player}} eligió el veneno. Gana el jugador {{winner}}.", lastBite: "Último mordisco: fila {{row}}, columna {{column}}", strategy: "Representa el tablero por las longitudes restantes de sus filas. Un estado es ganador cuando alguna mordida segura conduce a un estado perdedor; es perdedor cuando todas entregan un estado ganador al oponente. Construye la idea desde formas pequeñas para saber quién puede forzar el veneno sin revelar qué cuadro elegir.", winningState: "Quien tiene el turno puede forzar una victoria desde este estado.", losingState: "Con respuestas perfectas, el otro jugador puede forzar una victoria desde este estado.", finished: "El ganador ya está decidido; reinicia para clasificar otro estado." }
  },
  finish: { eyebrow: "Clase terminada", title: "Mantén el ciclo en movimiento.", description: "Marca esta guía como completada cuando hayas seguido la ruta. Puedes volver a abrirla cuando quieras; los juegos siempre comienzan desde cero.", markComplete: "Marcar guía como completada", markProgress: "Volver a en progreso", back: "Regresar a la ruta" },
  progress: { saveError: "No se inició el progreso", saveErrorDescription: "La guía sigue disponible por completo. Intenta de nuevo desde la ruta más tarde.", completed: "Introducción completada", completedDescription: "Tu ruta ahora muestra esta guía como completada.", inProgress: "Introducción reabierta", inProgressDescription: "Tu ruta ahora muestra esta guía en progreso.", updateError: "No se actualizó el progreso", updateErrorDescription: "Tu lección y tus juegos no cambiaron. Intenta la acción de nuevo." }
} as const;
